### ISSUE TITLE
Preauthorize opphold-innrapotering-web i dev-gcp

### ISSUE THREAD

**Issue by JGH153** [navikt/altinn-rettigheter-proxy#153]
Hei, vi ønsker å ta i bruk applikasjonen deres, kan dere pre-authorize den i dev-gcp?

```    
- application: institusjon-opphold-innrapportering-web
      namespace: team-rocket
      cluster: dev-gcp
```

**Comment by peterbb** [comment]
Hei! Ser at dette er gjort. Bare si i fra når dere trenger prod-tilgang. :)
